// <auto-generated />
using System;
using DATN_DT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DATN_DT.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20251111100919_lnl")]
    partial class lnl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DATN_DT.Models.AnhSanPham", b =>
                {
                    b.Property<int>("IdAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnh"));

                    b.Property<string>("DuongDan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdModelSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("ModelSanPhamIdModelSanPham")
                        .HasColumnType("int");

                    b.HasKey("IdAnh");

                    b.HasIndex("ModelSanPhamIdModelSanPham");

                    b.ToTable("AnhSanPhams");
                });

            modelBuilder.Entity("DATN_DT.Models.BaoHanh", b =>
                {
                    b.Property<int>("IdBaoHanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBaoHanh"));

                    b.Property<decimal?>("ChiPhiPhatSinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("IdImei")
                        .HasColumnType("int");

                    b.Property<int?>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("IdNhanVien")
                        .HasColumnType("int");

                    b.Property<int?>("ImeiIdImei")
                        .HasColumnType("int");

                    b.Property<int?>("KhachHangIdKhachHang")
                        .HasColumnType("int");

                    b.Property<string>("MoTaLoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NhanVienIdNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XuLy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBaoHanh");

                    b.HasIndex("ImeiIdImei");

                    b.HasIndex("KhachHangIdKhachHang");

                    b.HasIndex("NhanVienIdNhanVien");

                    b.ToTable("BaoHanhs");
                });

            modelBuilder.Entity("DATN_DT.Models.CameraSau", b =>
                {
                    b.Property<int>("IdCameraSau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCameraSau"));

                    b.Property<string>("DoPhanGiaiCamSau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaCamSau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuayVideoCamSau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoLuongOngKinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhNangCamSau")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCameraSau");

                    b.ToTable("CameraSaus");
                });

            modelBuilder.Entity("DATN_DT.Models.CameraTruoc", b =>
                {
                    b.Property<int>("IdCamTruoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCamTruoc"));

                    b.Property<string>("DoPhanGiaiCamTruoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaCamTruoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuayVideoCamTruoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhNangCamTruoc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCamTruoc");

                    b.ToTable("CameraTruocs");
                });

            modelBuilder.Entity("DATN_DT.Models.ChucVu", b =>
                {
                    b.Property<int>("IdChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChucVu"));

                    b.Property<string>("TenChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdChucVu");

                    b.ToTable("ChucVus");
                });

            modelBuilder.Entity("DATN_DT.Models.HoaDon", b =>
                {
                    b.Property<int>("IdHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHoaDon"));

                    b.Property<int?>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("IdKhuyenMai")
                        .HasColumnType("int");

                    b.Property<int?>("IdNhanVien")
                        .HasColumnType("int");

                    b.Property<int?>("KhachHangIdKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("KhuyenMaiIdKhuyenMai")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayLapHoaDon")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NhanVienIdNhanVien")
                        .HasColumnType("int");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiHoaDon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHoaDon");

                    b.HasIndex("KhachHangIdKhachHang");

                    b.HasIndex("KhuyenMaiIdKhuyenMai");

                    b.HasIndex("NhanVienIdNhanVien");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("DATN_DT.Models.HoaDonChiTiet", b =>
                {
                    b.Property<int>("IdHoaDonChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHoaDonChiTiet"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("HoaDonIdHoaDon")
                        .HasColumnType("int");

                    b.Property<int?>("IdHoaDon")
                        .HasColumnType("int");

                    b.Property<int?>("IdImei")
                        .HasColumnType("int");

                    b.Property<int?>("IdModelSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("ImeiIdImei")
                        .HasColumnType("int");

                    b.Property<int?>("ModelSanPhamIdModelSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdHoaDonChiTiet");

                    b.HasIndex("HoaDonIdHoaDon");

                    b.HasIndex("ImeiIdImei");

                    b.HasIndex("ModelSanPhamIdModelSanPham");

                    b.ToTable("HoaDonChiTiets");
                });

            modelBuilder.Entity("DATN_DT.Models.Imei", b =>
                {
                    b.Property<int>("IdImei")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImei"));

                    b.Property<int?>("IdModelSanPham")
                        .HasColumnType("int");

                    b.Property<string>("MaImei")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModelSanPhamIdModelSanPham")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdImei");

                    b.HasIndex("ModelSanPhamIdModelSanPham");

                    b.ToTable("Imeis");
                });

            modelBuilder.Entity("DATN_DT.Models.KhachHang", b =>
                {
                    b.Property<int>("IdKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKhachHang"));

                    b.Property<string>("DiaChiKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("EmailKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SdtKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKhachHang");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("DATN_DT.Models.Kho", b =>
                {
                    b.Property<int>("IdKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKho"));

                    b.Property<string>("DiaChiKho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKho")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKho");

                    b.ToTable("Khos");
                });

            modelBuilder.Entity("DATN_DT.Models.KhuyenMai", b =>
                {
                    b.Property<int>("IdKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKhuyenMai"));

                    b.Property<string>("ApDungVoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GiaTri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiGiam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaKhuyenMai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiKM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKhuyenMai");

                    b.ToTable("KhuyenMais");
                });

            modelBuilder.Entity("DATN_DT.Models.ManHinh", b =>
                {
                    b.Property<int>("IdManHinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdManHinh"));

                    b.Property<string>("CongNgheManHinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoPhanGiai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KichThuoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaMan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhNangMan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdManHinh");

                    b.ToTable("ManHinhs");
                });

            modelBuilder.Entity("DATN_DT.Models.ModelSanPham", b =>
                {
                    b.Property<int>("IdModelSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModelSanPham"));

                    b.Property<int?>("CameraSauIdCameraSau")
                        .HasColumnType("int");

                    b.Property<int?>("CameraTruocIdCamTruoc")
                        .HasColumnType("int");

                    b.Property<decimal?>("GiaBanModel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("IdCameraSau")
                        .HasColumnType("int");

                    b.Property<int?>("IdCameraTruoc")
                        .HasColumnType("int");

                    b.Property<int?>("IdManHinh")
                        .HasColumnType("int");

                    b.Property<int?>("IdPin")
                        .HasColumnType("int");

                    b.Property<int?>("IdRAM")
                        .HasColumnType("int");

                    b.Property<int?>("IdROM")
                        .HasColumnType("int");

                    b.Property<int?>("IdSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("ManHinhIdManHinh")
                        .HasColumnType("int");

                    b.Property<string>("Mau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PinIdPin")
                        .HasColumnType("int");

                    b.Property<int?>("RAMIdRAM")
                        .HasColumnType("int");

                    b.Property<int?>("ROMIdROM")
                        .HasColumnType("int");

                    b.Property<int?>("SanPhamIdSanPham")
                        .HasColumnType("int");

                    b.Property<string>("TenModel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdModelSanPham");

                    b.HasIndex("CameraSauIdCameraSau");

                    b.HasIndex("CameraTruocIdCamTruoc");

                    b.HasIndex("ManHinhIdManHinh");

                    b.HasIndex("PinIdPin");

                    b.HasIndex("RAMIdRAM");

                    b.HasIndex("ROMIdROM");

                    b.HasIndex("SanPhamIdSanPham");

                    b.ToTable("ModelSanPhams");
                });

            modelBuilder.Entity("DATN_DT.Models.NhanVien", b =>
                {
                    b.Property<int>("IdNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNhanVien"));

                    b.Property<int?>("ChucVuIdChucVu")
                        .HasColumnType("int");

                    b.Property<string>("DiaChiNV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdChucVu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SdtNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTaiKhoanNV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiNV")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNhanVien");

                    b.HasIndex("ChucVuIdChucVu");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("DATN_DT.Models.Pin", b =>
                {
                    b.Property<int>("IdPin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPin"));

                    b.Property<string>("CongNgheSac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DungLuongPin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiPin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaPin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPin");

                    b.ToTable("Pins");
                });

            modelBuilder.Entity("DATN_DT.Models.RAM", b =>
                {
                    b.Property<int>("IdRAM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRAM"));

                    b.Property<string>("DungLuongRAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaRAM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRAM");

                    b.ToTable("RAMs");
                });

            modelBuilder.Entity("DATN_DT.Models.ROM", b =>
                {
                    b.Property<int>("IdROM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdROM"));

                    b.Property<string>("DungLuongROM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaROM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdROM");

                    b.ToTable("ROMs");
                });

            modelBuilder.Entity("DATN_DT.Models.SanPham", b =>
                {
                    b.Property<int>("IdSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSanPham"));

                    b.Property<decimal?>("GiaGoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiaNiemYet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("IdThuongHieu")
                        .HasColumnType("int");

                    b.Property<string>("MaSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThuongHieuIdThuongHieu")
                        .HasColumnType("int");

                    b.Property<string>("TrangThaiSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("VAT")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdSanPham");

                    b.HasIndex("ThuongHieuIdThuongHieu");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("DATN_DT.Models.ThanhToan", b =>
                {
                    b.Property<int>("IdThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThanhToan"));

                    b.Property<string>("HinhThuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HoaDonIdHoaDon")
                        .HasColumnType("int");

                    b.Property<int?>("IdHoaDon")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdThanhToan");

                    b.HasIndex("HoaDonIdHoaDon");

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("DATN_DT.Models.ThuongHieu", b =>
                {
                    b.Property<int>("IdThuongHieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThuongHieu"));

                    b.Property<string>("TenThuongHieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiThuongHieu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdThuongHieu");

                    b.ToTable("ThuongHieus");
                });

            modelBuilder.Entity("DATN_DT.Models.TonKho", b =>
                {
                    b.Property<int>("IdTonKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTonKho"));

                    b.Property<int?>("IdKho")
                        .HasColumnType("int");

                    b.Property<int?>("IdModelSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("KhoIdKho")
                        .HasColumnType("int");

                    b.Property<int?>("ModelSanPhamIdModelSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdTonKho");

                    b.HasIndex("KhoIdKho");

                    b.HasIndex("ModelSanPhamIdModelSanPham");

                    b.ToTable("TonKhos");
                });

            modelBuilder.Entity("DonHang", b =>
                {
                    b.Property<int>("IdDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDonHang"));

                    b.Property<string>("DiaChiGiaoHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("KhachHangIdKhachHang")
                        .HasColumnType("int");

                    b.Property<string>("MaDon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiDH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiHoaDon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDonHang");

                    b.HasIndex("KhachHangIdKhachHang");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("DonHangChiTiet", b =>
                {
                    b.Property<int>("IdDonHangChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDonHangChiTiet"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DonHangIdDonHang")
                        .HasColumnType("int");

                    b.Property<int?>("IdDonHang")
                        .HasColumnType("int");

                    b.Property<int?>("IdKhuyenMai")
                        .HasColumnType("int");

                    b.Property<int?>("IdModelSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("KhuyenMaiIdKhuyenMai")
                        .HasColumnType("int");

                    b.Property<int?>("ModelSanPhamIdModelSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdDonHangChiTiet");

                    b.HasIndex("DonHangIdDonHang");

                    b.HasIndex("KhuyenMaiIdKhuyenMai");

                    b.HasIndex("ModelSanPhamIdModelSanPham");

                    b.ToTable("DonHangChiTiets");
                });

            modelBuilder.Entity("GioHang", b =>
                {
                    b.Property<int>("IdGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGioHang"));

                    b.Property<int?>("IdKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("KhachHangIdKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTaoGio")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiGio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGioHang");

                    b.HasIndex("KhachHangIdKhachHang");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("GioHangChiTiet", b =>
                {
                    b.Property<int>("IdGioHangChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGioHangChiTiet"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("GioHangIdGioHang")
                        .HasColumnType("int");

                    b.Property<int?>("IdGioHang")
                        .HasColumnType("int");

                    b.Property<int?>("IdModelSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("ModelSanPhamIdModelSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdGioHangChiTiet");

                    b.HasIndex("GioHangIdGioHang");

                    b.HasIndex("ModelSanPhamIdModelSanPham");

                    b.ToTable("GioHangChiTiets");
                });

            modelBuilder.Entity("DATN_DT.Models.AnhSanPham", b =>
                {
                    b.HasOne("DATN_DT.Models.ModelSanPham", "ModelSanPham")
                        .WithMany()
                        .HasForeignKey("ModelSanPhamIdModelSanPham");

                    b.Navigation("ModelSanPham");
                });

            modelBuilder.Entity("DATN_DT.Models.BaoHanh", b =>
                {
                    b.HasOne("DATN_DT.Models.Imei", "Imei")
                        .WithMany()
                        .HasForeignKey("ImeiIdImei");

                    b.HasOne("DATN_DT.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangIdKhachHang");

                    b.HasOne("DATN_DT.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienIdNhanVien");

                    b.Navigation("Imei");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DATN_DT.Models.HoaDon", b =>
                {
                    b.HasOne("DATN_DT.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangIdKhachHang");

                    b.HasOne("DATN_DT.Models.KhuyenMai", "KhuyenMai")
                        .WithMany()
                        .HasForeignKey("KhuyenMaiIdKhuyenMai");

                    b.HasOne("DATN_DT.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienIdNhanVien");

                    b.Navigation("KhachHang");

                    b.Navigation("KhuyenMai");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DATN_DT.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("DATN_DT.Models.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("HoaDonIdHoaDon");

                    b.HasOne("DATN_DT.Models.Imei", "Imei")
                        .WithMany()
                        .HasForeignKey("ImeiIdImei");

                    b.HasOne("DATN_DT.Models.ModelSanPham", "ModelSanPham")
                        .WithMany()
                        .HasForeignKey("ModelSanPhamIdModelSanPham");

                    b.Navigation("HoaDon");

                    b.Navigation("Imei");

                    b.Navigation("ModelSanPham");
                });

            modelBuilder.Entity("DATN_DT.Models.Imei", b =>
                {
                    b.HasOne("DATN_DT.Models.ModelSanPham", "ModelSanPham")
                        .WithMany()
                        .HasForeignKey("ModelSanPhamIdModelSanPham");

                    b.Navigation("ModelSanPham");
                });

            modelBuilder.Entity("DATN_DT.Models.ModelSanPham", b =>
                {
                    b.HasOne("DATN_DT.Models.CameraSau", "CameraSau")
                        .WithMany()
                        .HasForeignKey("CameraSauIdCameraSau");

                    b.HasOne("DATN_DT.Models.CameraTruoc", "CameraTruoc")
                        .WithMany()
                        .HasForeignKey("CameraTruocIdCamTruoc");

                    b.HasOne("DATN_DT.Models.ManHinh", "ManHinh")
                        .WithMany()
                        .HasForeignKey("ManHinhIdManHinh");

                    b.HasOne("DATN_DT.Models.Pin", "Pin")
                        .WithMany()
                        .HasForeignKey("PinIdPin");

                    b.HasOne("DATN_DT.Models.RAM", "RAM")
                        .WithMany()
                        .HasForeignKey("RAMIdRAM");

                    b.HasOne("DATN_DT.Models.ROM", "ROM")
                        .WithMany()
                        .HasForeignKey("ROMIdROM");

                    b.HasOne("DATN_DT.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamIdSanPham");

                    b.Navigation("CameraSau");

                    b.Navigation("CameraTruoc");

                    b.Navigation("ManHinh");

                    b.Navigation("Pin");

                    b.Navigation("RAM");

                    b.Navigation("ROM");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DATN_DT.Models.NhanVien", b =>
                {
                    b.HasOne("DATN_DT.Models.ChucVu", "ChucVu")
                        .WithMany()
                        .HasForeignKey("ChucVuIdChucVu");

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("DATN_DT.Models.SanPham", b =>
                {
                    b.HasOne("DATN_DT.Models.ThuongHieu", "ThuongHieu")
                        .WithMany()
                        .HasForeignKey("ThuongHieuIdThuongHieu");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("DATN_DT.Models.ThanhToan", b =>
                {
                    b.HasOne("DATN_DT.Models.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("HoaDonIdHoaDon");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("DATN_DT.Models.TonKho", b =>
                {
                    b.HasOne("DATN_DT.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("KhoIdKho");

                    b.HasOne("DATN_DT.Models.ModelSanPham", "ModelSanPham")
                        .WithMany()
                        .HasForeignKey("ModelSanPhamIdModelSanPham");

                    b.Navigation("Kho");

                    b.Navigation("ModelSanPham");
                });

            modelBuilder.Entity("DonHang", b =>
                {
                    b.HasOne("DATN_DT.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangIdKhachHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("DonHangChiTiet", b =>
                {
                    b.HasOne("DonHang", "DonHang")
                        .WithMany("DonHangChiTiets")
                        .HasForeignKey("DonHangIdDonHang");

                    b.HasOne("DATN_DT.Models.KhuyenMai", "KhuyenMai")
                        .WithMany()
                        .HasForeignKey("KhuyenMaiIdKhuyenMai");

                    b.HasOne("DATN_DT.Models.ModelSanPham", "ModelSanPham")
                        .WithMany()
                        .HasForeignKey("ModelSanPhamIdModelSanPham");

                    b.Navigation("DonHang");

                    b.Navigation("KhuyenMai");

                    b.Navigation("ModelSanPham");
                });

            modelBuilder.Entity("GioHang", b =>
                {
                    b.HasOne("DATN_DT.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangIdKhachHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("GioHangChiTiet", b =>
                {
                    b.HasOne("GioHang", "GioHang")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("GioHangIdGioHang");

                    b.HasOne("DATN_DT.Models.ModelSanPham", "ModelSanPham")
                        .WithMany()
                        .HasForeignKey("ModelSanPhamIdModelSanPham");

                    b.Navigation("GioHang");

                    b.Navigation("ModelSanPham");
                });

            modelBuilder.Entity("DATN_DT.Models.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("DonHang", b =>
                {
                    b.Navigation("DonHangChiTiets");
                });

            modelBuilder.Entity("GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });
#pragma warning restore 612, 618
        }
    }
}
